-- Depends on:
-- tables MNR.CELL,MNR.LANE,MNR.LAYER,MNR.SENSOR,MNR.SENSOR_MODEL,MNR.MATERIAL
--  views MNR.CELLS
CREATE OR REPLACE VIEW CELL_SENSORS AS
SELECT
CELLS.ID CELL_ID ,
CELLS.CELL ,
CELLS.DESIGN ,
CELLS.CELL_TYPE ,
CELLS.FROM_DATE ,
CELLS.CELL_END_DATE ,
LN.NAME LANE ,
M.BASIC_MATERIAL ,
ROUND((LY.THICKNESS/2.54),2) THICKNESS_IN ,
SM.MODEL ,
S.ID SENSOR_ID ,
S.SEQ ,
S.DATE_INSTALLED ,
S.DATE_REMOVED ,
S.SENSOR_DEPTH_IN
FROM
(
   SELECT
   ID ,
   CELL ,
   DESIGN_NUMBER DESIGN ,
   CELL_TYPE ,
   CONSTRUCTION_BEGAN_DATE FROM_DATE ,
   CELL_END_DATE CELL_END_DATE ,
   TO_NUMBER(TO_CHAR(CONSTRUCTION_BEGAN_DATE,'yyyy')) FROM_YEAR ,
   TO_NUMBER(TO_CHAR(CELL_END_DATE,'yyyy')) TO_YEAR
   FROM
   (
      SELECT
      ID ,
      CELL ,
      CELL_TYPE ,
      CONSTRUCTION_BEGAN_DATE ,
      CONSTRUCTION_ENDED_DATE ,
      CASE WHEN CELL=1 THEN NULL ELSE NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) END CELL_END_DATE ,
      DESIGN_NUMBER
      FROM
      (
         SELECT
         ID ,
         CELL_NUMBER CELL ,
         SUBSTR(CLASS,24) CELL_TYPE ,
         (SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE ,
         CONSTRUCTION_ENDED_DATE ,
         DEMOLISHED_DATE ,
         CASE WHEN LEAD
         (
            ID,1,NULL
         )
         OVER
         (
            PARTITION BY CELL_NUMBER
            ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
         )
         IS NULL THEN 1 WHEN LEAD
         (
            ID,2,NULL
         )
         OVER
         (
            PARTITION BY CELL_NUMBER
            ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
         )
         IS NULL THEN 2 WHEN LEAD
         (
            ID,3,NULL
         )
         OVER
         (
            PARTITION BY CELL_NUMBER
            ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
         )
         IS NULL THEN 3 WHEN LEAD
         (
            ID,4,NULL
         )
         OVER
         (
            PARTITION BY CELL_NUMBER
            ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
         )
         IS NULL THEN 4 WHEN LEAD
         (
            ID,5,NULL
         )
         OVER
         (
            PARTITION BY CELL_NUMBER
            ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
         )
         IS NULL THEN 5 ELSE 1 END DESIGN_NUMBER
         FROM MNR.CELL C
      )
   )
)
CELLS JOIN MNR.LANE LN ON LN.CELL_ID=CELLS.ID JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID JOIN MNR.SENSOR S ON S.LAYER_ID=LY.ID JOIN MNR.SENSOR_MODEL SM ON S.SENSOR_MODEL_ID=SM.ID JOIN MNR.MATERIAL M ON LY.MATERIAL_ID=M.ID
