-- Depends on:
-- tables MNR.FACILITY, MNR.ROAD_SECTION, MNR.CELL, MNR.LANE, MNR.LAYER, MNR.SENSOR, MNR.SENSOR_MODEL, MNR.MATERIAL 
--  views MNR.CELL_SUMMARY, MNR.DEPTH_RANGE
CREATE OR REPLACE VIEW CELL_SENSOR_PROPS AS
SELECT
T.CELL, T.TYPE, T.LOCATION , CASE WHEN T.CELL_END_DATE IS NOT NULL
AND T.DATE_INSTALLED > T.CELL_END_DATE THEN T.CELL_END_DATE+1 ELSE T.FIRST_LAYER_DATE END CELL_FROM_DATE ,
NVL(T.CELL_END_DATE,SYSDATE) CELL_TO_DATE ,
T.MAT ,
T.THICKNESS ,
T.MODEL ,
T.SENSOR_ID ,
T.SEQ ,
T.DATE_INSTALLED ,
T.DATE_REMOVED ,
ROW_NUMBER() OVER (PARTITION BY T.CELL ORDER BY T.STATION,T.OFFSET,T.DEPTH) SENSOR_IDX ,
T.STATION ,
T.OFFSET ,
T.DEPTH ,
T.DEPTH_GROUP
FROM
(
   SELECT
   C.CELL_NUMBER CELL ,
   SUBSTR(C.CLASS,24) TYPE ,
   F.NAME LOCATION ,
   DEPTH_GROUP ,
   DESCR DEPTH_GROUP_DESCR ,
   M.DESCRIPTION MAT ,
   LY.THICKNESS/25.4 THICKNESS ,
   CD.CONSTRUCTION_ENDED_DATE FIRST_LAYER_DATE ,
   CD.TO_DATE CELL_END_DATE ,
   SM.MODEL ,
   S.ID SENSOR_ID ,
   S.SEQ ,
   ROUND((S.SENSOR_DEPTH_IN/12),4) DEPTH ,
   S.DATE_INSTALLED ,
   S.DATE_REMOVED ,
   S.STATION_FT STATION ,
   S.OFFSET_FT OFFSET
   FROM MNR.CELL C JOIN MNR.LANE LN ON LN.CELL_ID=C.ID JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID JOIN MNR.SENSOR S ON S.LAYER_ID=LY.ID JOIN MNR.SENSOR_MODEL SM ON S.SENSOR_MODEL_ID=SM.ID JOIN MNR.MATERIAL M ON LY.MATERIAL_ID=M.ID JOIN MNR.ROAD_SECTION R ON C.ROAD_SECTION_ID=R.ID JOIN MNR.FACILITY F ON R.FACILITY_ID=F.ID JOIN MNR.CELL_SUMMARY CD ON CD.ID=C.ID JOIN MNR.DEPTH_RANGE R ON ROUND
   (
      (S.SENSOR_DEPTH_IN/12),4
   )
   BETWEEN NVL(R.RNG_START, ROUND((S.SENSOR_DEPTH_IN/12),4))
   AND NVL(R.RNG_STOP, ROUND((S.SENSOR_DEPTH_IN/12),4))
)
T JOIN MNR.SENSOR_SUM_BY_SEQ D ON D.CELL=T.CELL
AND D.STATION=T.STATION
AND D.OFFSET=T.OFFSET
AND D.MODEL=T.MODEL
