-- Depends on:
-- tables MNR.CELL,MNR.LANE,MNR.LAYER
CREATE OR REPLACE VIEW CELL_SUMMARY AS
SELECT
ID ,
CELL,
FIRST_LAYER_DATE,
LAST_LAYER_DATE,
CONSTRUCTION_ENDED_DATE,
CELL_END_DATE TO_DATE,
TYPE,
DESIGN_NUMBER
FROM
(
   SELECT
   ID ,
   CELL,
   CELL_TYPE TYPE,
   FIRST_LAYER_DATE,
   LAST_LAYER_DATE,
   CONSTRUCTION_ENDED_DATE,
   NVL(DEMOLISHED_DATE,LEAD(FIRST_LAYER_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY FIRST_LAYER_DATE)) CELL_END_DATE,
   DESIGN_NUMBER
   FROM
   (
      SELECT
      ID ,
      CELL_NUMBER CELL ,
      SUBSTR(CLASS,24) CELL_TYPE ,
      (SELECT MIN(SL.CONSTRUCT_START_DATE) FROM MNR.CELL SC JOIN MNR.LANE SLN ON SLN.CELL_ID=SC.ID JOIN MNR.LAYER SL ON SL.LANE_ID=SLN.ID WHERE SC.ID=C.ID) FIRST_LAYER_DATE ,
      (SELECT MAX(SL.CONSTRUCT_START_DATE) FROM MNR.CELL SC JOIN MNR.LANE SLN ON SLN.CELL_ID=SC.ID JOIN MNR.LAYER SL ON SL.LANE_ID=SLN.ID WHERE SC.ID=C.ID) LAST_LAYER_DATE ,
      CONSTRUCTION_ENDED_DATE ,
      DEMOLISHED_DATE ,
      CASE WHEN LEAD
      (
         ID,1,NULL
      )
      OVER
      (
         PARTITION BY CELL_NUMBER
         ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
      )
      IS NULL THEN 1 WHEN LEAD
      (
         ID,2,NULL
      )
      OVER
      (
         PARTITION BY CELL_NUMBER
         ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
      )
      IS NULL THEN 2 WHEN LEAD
      (
         ID,3,NULL
      )
      OVER
      (
         PARTITION BY CELL_NUMBER
         ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
      )
      IS NULL THEN 3 WHEN LEAD
      (
         ID,4,NULL
      )
      OVER
      (
         PARTITION BY CELL_NUMBER
         ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
      )
      IS NULL THEN 4 WHEN LEAD
      (
         ID,5,NULL
      )
      OVER
      (
         PARTITION BY CELL_NUMBER
         ORDER BY C.CONSTRUCTION_ENDED_DATE DESC
      )
      IS NULL THEN 5 ELSE 1 END DESIGN_NUMBER
      FROM MNR.CELL C
   )
)
