CREATE OR REPLACE VIEW ORPHAN_DISTRESSES_COUNTS AS
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_AC                   ' table_name
FROM MNR.DISTRESS_AC
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_AGG_SURVEY_SEMI      ' table_name
FROM MNR.DISTRESS_AGG_SURVEY_SEMI
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_ALPS_RESULTS_RUT     ' table_name
FROM MNR.DISTRESS_ALPS_RESULTS_RUT
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_CIRCULR_TEXTR_METER  ' table_name
FROM MNR.DISTRESS_CIRCULR_TEXTR_METER
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_CUPPING              ' table_name
FROM MNR.DISTRESS_CUPPING
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_FRICTION_DFT         ' table_name
FROM MNR.DISTRESS_FRICTION_DFT
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_FRICTION_TRAILER     ' table_name
FROM MNR.DISTRESS_FRICTION_TRAILER
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_JPCC                 ' table_name
FROM MNR.DISTRESS_JPCC
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_LANE_SHOULDER_DROPOFF' table_name
FROM MNR.DISTRESS_LANE_SHOULDER_DROPOFF
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_NUCLEAR_DENSITY      ' table_name
FROM MNR.DISTRESS_NUCLEAR_DENSITY
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_OBSI_DATA            ' table_name
FROM MNR.DISTRESS_OBSI_DATA
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_OBSI_SUMMARY         ' table_name
FROM MNR.DISTRESS_OBSI_SUMMARY
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_PCC_FAULTS           ' table_name
FROM MNR.DISTRESS_PCC_FAULTS
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_PERMEABILITY_DIRECT  ' table_name
FROM MNR.DISTRESS_PERMEABILITY_DIRECT
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_RIDE_LISA            ' table_name
FROM MNR.DISTRESS_RIDE_LISA
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_RIDE_PATHWAYS        ' table_name
FROM MNR.DISTRESS_RIDE_PATHWAYS
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_RIDE_PAVETECH        ' table_name
FROM MNR.DISTRESS_RIDE_PAVETECH
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_RUTTING_DIPSTICK     ' table_name
FROM MNR.DISTRESS_RUTTING_DIPSTICK
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_RUTTING_STRAIGHT_EDGE' table_name
FROM MNR.DISTRESS_RUTTING_STRAIGHT_EDGE
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_SAND_PATCH           ' table_name
FROM MNR.DISTRESS_SAND_PATCH
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_SCHMIDT_HAMMER       ' table_name
FROM MNR.DISTRESS_SCHMIDT_HAMMER
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_SOUND_ABSORPTION     ' table_name
FROM MNR.DISTRESS_SOUND_ABSORPTION
where id is null
UNION
ALL
SELECT
count(*) ORPHAN_ROW_COUNT,'DISTRESS_WATER_PERMEABILITY   ' table_name
FROM MNR.DISTRESS_WATER_PERMEABILITY
where id is null
