DROP TABLE MNR.JOB_SETUP                PURGE;
DROP TABLE MNR.JOB_RESULT               PURGE;
--DROP TABLE JSEC_ROLE_PERMISSION_REL PURGE;
--DROP TABLE JSEC_USER_PERMISSION_REL PURGE;
--DROP TABLE JSEC_PERMISSION          PURGE;
--DROP TABLE JSEC_USER_ROLE_REL       PURGE;
--DROP TABLE JSEC_USER                PURGE;
--DROP TABLE JSEC_ROLE                PURGE;
exit;