SELECT CS.CELL, CS.DESIGN, MIN(FROM_DATE) FROM_DATE, MAX(CELL_END_DATE) TO_DATE, MIN(SEQ) FROM_SEQ, MAX(SEQ) TO_SEQ, COUNT(SEQ) NUM_SENSORS FROM 
(SELECT CELLS.ID, CELLS.CELL, CELLS.DESIGN, CELLS.FROM_DATE, CELLS.CELL_END_DATE, LN.NAME LANE, M.BASIC_MATERIAL, ROUND((LY.THICKNESS/2.54),2) THICKNESS_IN, SM.MODEL, S.SEQ, S.DATE_INSTALLED, S.DATE_REMOVED,S.SENSOR_DEPTH_IN 
	FROM (SELECT ID,CELL,DESIGN_NUMBER DESIGN,CONSTRUCTION_BEGAN_DATE FROM_DATE, CELL_END_DATE CELL_END_DATE,TO_NUMBER(TO_CHAR(CONSTRUCTION_BEGAN_DATE,'yyyy')) FROM_YEAR,TO_NUMBER(TO_CHAR(CELL_END_DATE,'yyyy')) TO_YEAR 
		FROM (SELECT ID,CELL,CELL_TYPE,CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE, CASE WHEN CELL=1 THEN NULL ELSE NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) END CELL_END_DATE,DESIGN_NUMBER 
			FROM (SELECT ID,CELL_NUMBER CELL,SUBSTR(CLASS,24) CELL_TYPE,(SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE,DEMOLISHED_DATE,CASE WHEN LEAD(ID,1,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 1WHEN LEAD(ID,2,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 2WHEN LEAD(ID,3,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 3WHEN LEAD(ID,4,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 4WHEN LEAD(ID,5,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 5ELSE 1 END DESIGN_NUMBER 
				FROM MNR.CELL C))) CELLS 
				JOIN MNR.LANE LN ON LN.CELL_ID=CELLS.ID 
				JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID 
				JOIN MNR.SENSOR S ON S.LAYER_ID=LY.ID 
				JOIN MNR.SENSOR_MODEL SM ON S.SENSOR_MODEL_ID=SM.ID 
				JOIN MNR.MATERIAL M ON LY.MATERIAL_ID=M.ID 
		  WHERE LN.NAME NOT LIKE '%Shldr' AND SM.MODEL='TC') 
CS GROUP BY CELL,DESIGN ORDER BY CELL,DESIGN,FROM_DATE



SELECT T.CELL,T.NUM_SENSORS,T.TREE,S.STATION_FT,S.OFFSET_FT,MIN(S.SEQ),MAX(S.SEQ) FROM TC_TREE T
JOIN MNR.SENSOR S ON T.STATION=S.STATION_FT AND T.OFFSET=S.OFFSET_FT
GROUP BY T.CELL,T.NUM_SENSORS,T.TREE,S.STATION_FT,S.OFFSET_FT
ORDER BY T.CELL,T.NUM_SENSORS,T.TREE,S.STATION_FT,S.OFFSET_FT		  

--------------------------------------------
CREATE OR REPLACE VIEW TC_TREE AS
SELECT B.ID,B.CELL_NUMBER CELL,B.STATION_FT STATION,B.OFFSET_FT OFFSET,B.SEQ_MIN,B.SEQ_MAX,B.NUM_SENSORS
, RANK() OVER (PARTITION BY CELL_NUMBER ORDER BY STATION_FT) TREE
FROM (
SELECT C.ID,C.CELL_NUMBER
,S.STATION_FT, S.OFFSET_FT, MIN(SEQ) SEQ_MIN, MAX(SEQ) SEQ_MAX, COUNT(*) NUM_SENSORS
FROM MNR.CELL C
JOIN MNR.LANE LN ON LN.CELL_ID=C.ID
JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID
JOIN MNR.SENSOR S ON S.LAYER_ID=LY.ID
JOIN MNR.SENSOR_MODEL SM ON S.SENSOR_MODEL_ID=SM.ID
WHERE SM.MODEL='TC'
GROUP BY C.ID,C.CELL_NUMBER,S.STATION_FT, S.OFFSET_FT
ORDER BY C.ID,C.CELL_NUMBER,S.STATION_FT, S.OFFSET_FT
) B
ORDER BY CELL,ID
-----------------------------------------------------------------------
SELECT CS.CELL, CS.DESIGN, MIN(FROM_DATE) LAYER_FROM_DATE, MAX(CELL_END_DATE) LAYER_TO_DATE, MIN(SEQ) FROM_SEQ, MAX(SEQ) TO_SEQ, COUNT(SEQ) NUM_SENSORS FROM (
SELECT CELLS.ID, CELLS.CELL, CELLS.DESIGN, CELLS.FROM_DATE, CELLS.CELL_END_DATE, LN.NAME LANE, M.BASIC_MATERIAL, ROUND((LY.THICKNESS/2.54),2) THICKNESS_IN, SM.MODEL, S.SEQ, S.DATE_INSTALLED, S.DATE_REMOVED,S.SENSOR_DEPTH_IN FROM (SELECT ID,CELL,DESIGN_NUMBER DESIGN,CONSTRUCTION_BEGAN_DATE FROM_DATE, CELL_END_DATE CELL_END_DATE,TO_NUMBER(TO_CHAR(CONSTRUCTION_BEGAN_DATE,'yyyy')) FROM_YEAR,TO_NUMBER(TO_CHAR(CELL_END_DATE,'yyyy')) TO_YEAR FROM (SELECT ID,CELL,CELL_TYPE,CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE, CASE WHEN CELL=1 THEN NULL ELSE NVL(DEMOLISHED_DATE,LEAD(CONSTRUCTION_BEGAN_DATE-1,1,NULL) OVER (PARTITION BY CELL ORDER BY CONSTRUCTION_BEGAN_DATE)) END CELL_END_DATE,DESIGN_NUMBER FROM (SELECT ID,CELL_NUMBER CELL,SUBSTR(CLASS,24) CELL_TYPE,(SELECT FIRST_LAYER_DATE FROM MNR.CELLS WHERE ID=C.ID) CONSTRUCTION_BEGAN_DATE,CONSTRUCTION_ENDED_DATE,DEMOLISHED_DATE,CASE WHEN LEAD(ID,1,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 1WHEN LEAD(ID,2,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 2WHEN LEAD(ID,3,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 3WHEN LEAD(ID,4,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 4WHEN LEAD(ID,5,NULL) OVER (PARTITION BY CELL_NUMBER ORDER BY C.CONSTRUCTION_ENDED_DATE DESC) IS NULL THEN 5ELSE 1 END DESIGN_NUMBER FROM MNR.CELL C))) CELLS JOIN MNR.LANE LN ON LN.CELL_ID=CELLS.ID JOIN MNR.LAYER LY ON LY.LANE_ID=LN.ID JOIN MNR.SENSOR S ON S.LAYER_ID=LY.ID JOIN MNR.SENSOR_MODEL SM ON S.SENSOR_MODEL_ID=SM.ID JOIN MNR.MATERIAL M ON LY.MATERIAL_ID=M.ID WHERE LN.NAME NOT LIKE '%Shldr' AND SM.MODEL='TC'
and s.date_installed > CELLS.CELL_END_DATE
) CS GROUP BY CS.CELL,CS.DESIGN ORDER BY CS.CELL,CS.DESIGN,LAYER_FROM_DATE
